### ISSUE TITLE
How to subscribe?

### ISSUE THREAD

**Issue by emnrd-ito** [julioromano/RxLocation#1]
I don't see an example of how to actually subscribe an observable. Am I missing it? Looking in the code, I see TestSubscriber used in a unit test, but that's not appropriate for actual code of course. I see a class called SafeSubscriber, but it doesn't have a create() method.

Another library using ReactiveX for location purposes is this one:
https://github.com/mcharmas/Android-ReactiveLocation
On that page there is an example with both the set up and the subscription.

**Comment by julioromano** [comment]
There's an example code snippet in the read me file: https://github.com/julioromano/RxLocation/blob/v0.10.0-beta/README.md
